general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "zellij"
args = ["options", "--default-shell", "nu"]

[window]
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = false

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "P", mods = "Control", action = "ReceiveChar" },
  { key = "Q", mods = "Control", action = "ReceiveChar" },
]
