#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias
alias e='eza --all --long --git --icons --group-directories-first --header --smart-group'

alias ca='cargo mommy'
alias cacu='ca install-update -l'
alias ucap='ca install-update -a'

alias v='nvim'

alias cbat='bat --decorations never'
alias cg='cd $(git rev-parse --show-toplevel)'

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/home/valentin/.bun/bin:$PATH"

# to make sure that TUIs on ssh servers run correct (e.g. journalctl)
export TERM=xterm-256color

eval "$(starship init bash)"
