#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias
alias e='eza --all --long --git --icons --group-directories-first --header --smart-group'

alias ca='cargo mommy'
alias cacu='ca install-update -l'
alias ucap='ca install-update -a'

alias vim='nvim'
alias v='nvim .'

alias cbat='bat --decorations never'
alias cg='cd $(git rev-parse --show-toplevel)'

export PATH="$HOME/.cargo/bin:$PATH"

eval "$(starship init bash)"
