#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias
alias l='eza --all --long --git --icons --group-directories-first --header --smart-group'
alias e='l'
alias ca='cargo mommy'
alias cacu='ca install-update -l'
alias ucap='ca install-update -a'
alias vim='nvim'
alias v='nvim .'
alias cbat='bat --decorations never'
alias cg='cd $(git rev-parse --show-toplevel)'
alias sysstat='sudo systemctl status'
alias sysen='sudo systemctl enable'
alias sysdis='sudo systemctl disable'
alias sysstart='sudo systemctl start'
alias sysrest='sudo systemctl restart'
alias sysstop='sudo systemctl stop'

export PATH="$HOME/.cargo/bin:$PATH"

eval "$(starship init bash)"
