# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 15
truncation_symbol = '…/'
truncate_to_repo = false
style = "blue bold"

[username]
show_always = true
style_user = "cyan bold"